version: "3.9"

services:
  my-priorities:
    image: ${IMAGE}
    networks:
      - traefik_swarm_nw
    labels:
      - traefik.enable=true
      - traefik.http.routers.priorities-traefik-router.rule=Host(`${DEPLOY_HOST}`)
      - traefik.http.routers.priorities-traefik-router.entrypoints=web,websecure
      - traefik.http.routers.priorities-traefik-router.tls=true
      - traefik.http.routers.priorities-traefik-router.tls.certresolver=${TRAEFIK_CERT_RESOLVER}
      - traefik.http.routers.priorities-traefik-router.service=priorities-traefik-service
      - traefik.http.services.priorities-traefik-service.loadbalancer.server.port=80
      - traefik.http.middlewares.priorities-traefik-middleware.headers.SSLRedirect=true
      - traefik.http.middlewares.priorities-traefik-middleware.headers.STSSeconds=315360000
      - traefik.http.middlewares.priorities-traefik-middleware.headers.browserXSSFilter=true
      - traefik.http.middlewares.priorities-traefik-middleware.headers.contentTypeNosniff=true
      - traefik.http.middlewares.priorities-traefik-middleware.headers.forceSTSHeader=true
      - traefik.http.middlewares.priorities-traefik-middleware.headers.SSLHost=${SSL_HOST}
      - traefik.http.middlewares.priorities-traefik-middleware.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.priorities-traefik-middleware.headers.STSPreload=true
      - traefik.http.routers.priorities-traefik-router.middlewares=priorities-traefik-middleware@docker
    environment:
      - Auth__AllowedEmails__0=${ALLOWED_EMAIL_1}
      - Auth__AllowedEmails__1=${ALLOWED_EMAIL_2}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
    volumes:
      - priorities-data:/data

volumes:
  priorities-data:
    external: true

networks:
  traefik_swarm_nw:
    external: true
